// import tableReportIconBlue from "../assets/images/table-report-icon-blue.svg";
// import tableReportIconGreen from "../assets/images/table-report-icon-green.svg";
// import tableReportIconRed from "../assets/images/table-report-icon-red.svg";
// import tableReportIconYellow from "../assets/images/table-report-icon-yellow.svg";
import ProfileImg1 from "../assets/images/recent_activity_img1.svg";
import ProfileImg2 from "../assets/images/recent_activity_img2.svg";
import DesignerImg from "../assets/images/image 54.svg";
import { APP_URL } from "./url";
import { FiHome, FiUsers } from "react-icons/fi";
import { BsLightningCharge } from "react-icons/bs";
import { PiEnvelopeLight } from "react-icons/pi";
import { IoCalendarClearOutline, IoColorPaletteOutline } from "react-icons/io5";

export const ProjectList = [
  {
    id: 1,
    label1: "Brand",
    BrandName: "Zomato",
    label2: "Designer",
    DesignerImg: DesignerImg,
    designerName: "Veronica Paul",
    label3: "Deadline",
    deadline: "30 Nov, 2024",
    label4: "Representer",
    representer: "Rupesh Kumar",

    priorityLabel: ["Low", "Medium", "High"],
  },
  {
    id: 2,
    label1: "Brand",
    BrandName: "Zomato",
    label2: "Designer",
    DesignerImg: DesignerImg,
    designerName: "Veronica Paul",
    label3: "Deadline",
    deadline: "15 Dec, 2024",
    label4: "Representer",
    representer: "Rupesh Kumar",
    priorityLabel: ["Medium", "Low", "High"],
  },
  {
    id: 3,
    label1: "Brand",
    BrandName: "Zomato",
    label2: "Designer",
    DesignerImg: DesignerImg,
    designerName: "Veronica Paul",
    label3: "Deadline",
    deadline: "20 Dec, 2024",
    label4: "Representer",
    representer: "Rupesh Kumar",
    priorityLabel: ["Medium", "High", "Low"],
  },
  {
    id: 4,
    label1: "Brand",
    BrandName: "Zomato",
    label2: "Designer",
    DesignerImg: DesignerImg,
    designerName: "Veronica Paul",
    label3: "Deadline",
    deadline: "10 Jan, 2025",
    label4: "Representer",
    representer: "Rupesh Kumar",
    priorityLabel: ["High", "Medium", "Low"],
  },
  {
    id: 5,
    label1: "Brand",
    BrandName: "Zomato",
    label2: "Designer",
    DesignerImg: DesignerImg,
    designerName: "Veronica Paul",
    label3: "Deadline",
    deadline: "25 Jan, 2025",
    label4: "Representer",
    representer: "Rupesh Kumar",
    priorityLabel: ["Low", "High", "Medium"],
  },
  {
    id: 6,
    label1: "Brand",
    BrandName: "Zomato",
    label2: "Designer",
    DesignerImg: DesignerImg,
    designerName: "Veronica Paul",
    label3: "Deadline",
    deadline: "5 Feb, 2025",
    label4: "Representer",
    representer: "Rupesh Kumar",
    priorityLabel: ["Medium", "Low", "High"],
  },
  {
    id: 7,
    label1: "Brand",
    BrandName: "Zomato",
    label2: "Designer",
    DesignerImg: DesignerImg,
    designerName: "Veronica Paul",
    label3: "Deadline",
    deadline: "15 Feb, 2025",
    label4: "Representer",
    representer: "Rupesh Kumar",
    priorityLabel: ["High", "Low", "Medium"],
  },
  {
    id: 8,
    label1: "Brand",
    BrandName: "Zomato",
    label2: "Designer",
    DesignerImg: DesignerImg,
    designerName: "Veronica Paul",
    label3: "Deadline",
    deadline: "22 Feb, 2025",
    label4: "Representer",
    representer: "Rupesh Kumar",
    priorityLabel: ["Medium", "High", "Low"],
  },
  {
    id: 9,
    label1: "Brand",
    BrandName: "Zomato",
    label2: "Designer",
    DesignerImg: DesignerImg,
    designerName: "Veronica Paul",
    label3: "Deadline",
    deadline: "5 Mar, 2025",
    label4: "Representer",
    representer: "Rupesh Kumar",
    priorityLabel: ["Low", "High", "Medium"],
  },
  {
    id: 10,
    label1: "Brand",
    BrandName: "Zomato",
    label2: "Designer",
    DesignerImg: DesignerImg,
    designerName: "Veronica Paul",
    label3: "Deadline",
    deadline: "12 Mar, 2025",
    label4: "Representer",
    representer: "Rupesh Kumar",
    priorityLabel: ["High", "Medium", "Low"],
  },
  {
    id: 11,
    label1: "Brand",
    BrandName: "Zomato",
    label2: "Designer",
    DesignerImg: DesignerImg,
    designerName: "Veronica Paul",
    label3: "Deadline",
    deadline: "15 Mar, 2025",
    label4: "Representer",
    representer: "Rupesh Kumar",
    priorityLabel: ["Low", "Medium", "High"],
  },
  {
    id: 12,
    label1: "Brand",
    BrandName: "Zomato",
    label2: "Designer",
    DesignerImg: DesignerImg,
    designerName: "Veronica Paul",
    label3: "Deadline",
    deadline: "28 Mar, 2025",
    label4: "Representer",
    representer: "Rupesh Kumar",
    priorityLabel: ["Medium", "Low", "High"],
  },
  {
    id: 13,
    label1: "Brand",
    BrandName: "Zomato",
    label2: "Designer",
    DesignerImg: DesignerImg,
    designerName: "Veronica Paul",
    label3: "Deadline",
    deadline: "2 Apr, 2025",
    label4: "Representer",
    representer: "Rupesh Kumar",
    priorityLabel: ["High", "Low", "Medium"],
  },
  {
    id: 14,
    label1: "Brand",
    BrandName: "Zomato",
    label2: "Designer",
    DesignerImg: DesignerImg,
    designerName: "Veronica Paul",
    label3: "Deadline",
    deadline: "10 Apr, 2025",
    label4: "Representer",
    representer: "Rupesh Kumar",
    priorityLabel: ["Low", "High", "Medium"],
  },
  {
    id: 15,
    label1: "Brand",
    BrandName: "Zomato",
    label2: "Designer",
    DesignerImg: DesignerImg,
    designerName: "Veronica Paul",
    label3: "Deadline",
    deadline: "20 Apr, 2025",
    label4: "Representer",
    representer: "Rupesh Kumar",
    priorityLabel: ["Medium", "High", "Low"],
  },
];
export const projectsData = [
  {
    img: ProfileImg1,
    details: "Albert Russel marked Illustration design as completed.",
    time: "1:12 pm",
  },
  {
    img: ProfileImg2,
    details:
      "Creator Sarah Miller assigned to the task Website Design requested by Jhon David.",
    time: "1:12 pm",
  },
];
export const MENU_ITEMS = [
  {
    name: "home",
    url: APP_URL.HOME,
    icon: FiHome,
  },
  {
    name: "projects",
    url: APP_URL.PROJECTS,
    icon: IoColorPaletteOutline,
    subMenu: [
      {
        name: "Open Projects",
        url: APP_URL.PROJECTS + "/sub-project-1",
      },
      {
        name: "Closed Projects",
        url: APP_URL.PROJECTS + "/sub-project-2",
      },
    ],
  },
  {
    name: "your-team",
    url: APP_URL.YOUR_TEAM,
    icon: FiUsers,
    subMenu: [
      {
        name: "Creators",
        url: APP_URL.YOUR_TEAM + "/sub-project-1",
      },
      {
        name: "Brands",
        url: APP_URL.YOUR_TEAM + "/sub-project-2",
      },
    ],
  },
  {
    name: "escalate",
    url: APP_URL.ESCALATE,
    icon: BsLightningCharge,
  },
  {
    name: "index",
    url: APP_URL.INDEX,
    icon: PiEnvelopeLight,
  },
  {
    name: "meetings",
    url: APP_URL.MEETINGS,
    icon: IoCalendarClearOutline,
  },
];
